version: '3'
services:
  local-db:
    image: mysql:latest
    container_name: ilsanPark
    restart: always
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Seoul
    volumes:
      - db_data:/var/lib/mysql
    platform: linux/amd64

volumes:
  db_data:
